# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence


stages:
  - test
  - report
#  - convert

sast:
  stage: test
  artifacts:
    reports:
      sast: gl-sast-report.json
    paths:
      - gl-sast-report.json

include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml

build_report:
  stage: report
  image: python:3.10-slim
  before_script:
    - pip install requests
  script:
    - DIR=$(pwd)
    - ls $DIR
    - python security_test/global_report_builder.py $DIR/gl-sast-report.json
  artifacts:
    paths:
      - report.html

# pdf_conversion:
#   stage: convert
#   image: alpine
#   before_script:
#     - apk add --no-cache chromium --repository=http://dl-cdn.alpinelinux.org/alpine/v3.10/main
#   script:
#     - DIR=$(pwd)
#     - chromium --headless --disable-gpu --no-sandbox --print-to-pdf file://$DIR/report.html
#   artifacts:
#     paths:
#       - output.pdf